/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the homepage.
   */
  slug: string;
  /**
   * Off by default so editing stays content-only. Turn on to reveal per-breakpoint placement, sizing and animation.
   */
  showDesignControls?: boolean | null;
  layout?: CanvasSectionBlock[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CanvasSectionBlock".
 */
export interface CanvasSectionBlock {
  /**
   * Admin only.
   */
  title?: string | null;
  background?: string | null;
  desktopHeight: number;
  tabletHeight: number;
  mobileHeight: number;
  hideOnDesktop?: boolean | null;
  hideOnTablet?: boolean | null;
  hideOnMobile?: boolean | null;
  fullBleed?: boolean | null;
  layers?:
    | {
        type: 'text' | 'image' | 'button';
        /**
         * Only used to identify this layer in the admin list.
         */
        label?: string | null;
        /**
         * Line breaks are preserved.
         */
        text?: string | null;
        buttonLabel?: string | null;
        variant?: ('solid' | 'outline') | null;
        href?: string | null;
        newTab?: boolean | null;
        image?: (number | null) | Media;
        imageAlt?: string | null;
        objectFit?: ('contain' | 'cover' | 'fill') | null;
        /**
         * Base placement. Coordinates are in design pixels (canvas width 1280).
         */
        desktop: {
          visibility?: ('visible' | 'hidden') | null;
          anchor: 'tl' | 'tc' | 'tr' | 'ml' | 'mc' | 'mr' | 'bl' | 'bc' | 'br';
          x?: number | null;
          y?: number | null;
          w?: number | null;
          h?: number | null;
          fontSize?: number | null;
          lineHeight?: number | null;
          fontWeight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '900') | null;
          letterSpacing?: number | null;
          align?: ('right' | 'center' | 'left') | null;
          color?: string | null;
        };
        /**
         * Leave a field blank to inherit the desktop value.
         */
        tablet?: {
          visibility?: ('inherit' | 'visible' | 'hidden') | null;
          anchor?: ('tl' | 'tc' | 'tr' | 'ml' | 'mc' | 'mr' | 'bl' | 'bc' | 'br') | null;
          x?: number | null;
          y?: number | null;
          w?: number | null;
          h?: number | null;
          fontSize?: number | null;
          lineHeight?: number | null;
          fontWeight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '900') | null;
          letterSpacing?: number | null;
          align?: ('right' | 'center' | 'left') | null;
          color?: string | null;
        };
        /**
         * Leave a field blank to inherit the desktop value.
         */
        mobile?: {
          visibility?: ('inherit' | 'visible' | 'hidden') | null;
          anchor?: ('tl' | 'tc' | 'tr' | 'ml' | 'mc' | 'mr' | 'bl' | 'bc' | 'br') | null;
          x?: number | null;
          y?: number | null;
          w?: number | null;
          h?: number | null;
          fontSize?: number | null;
          lineHeight?: number | null;
          fontWeight?: ('100' | '200' | '300' | '400' | '500' | '600' | '700' | '900') | null;
          letterSpacing?: number | null;
          align?: ('right' | 'center' | 'left') | null;
          color?: string | null;
        };
        animation?: ('none' | 'fade' | 'up' | 'down' | 'left' | 'right') | null;
        delay?: number | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'canvasSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showDesignControls?: T;
  layout?:
    | T
    | {
        canvasSection?: T | CanvasSectionBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CanvasSectionBlock_select".
 */
export interface CanvasSectionBlockSelect<T extends boolean = true> {
  title?: T;
  background?: T;
  desktopHeight?: T;
  tabletHeight?: T;
  mobileHeight?: T;
  hideOnDesktop?: T;
  hideOnTablet?: T;
  hideOnMobile?: T;
  fullBleed?: T;
  layers?:
    | T
    | {
        type?: T;
        label?: T;
        text?: T;
        buttonLabel?: T;
        variant?: T;
        href?: T;
        newTab?: T;
        image?: T;
        imageAlt?: T;
        objectFit?: T;
        desktop?:
          | T
          | {
              visibility?: T;
              anchor?: T;
              x?: T;
              y?: T;
              w?: T;
              h?: T;
              fontSize?: T;
              lineHeight?: T;
              fontWeight?: T;
              letterSpacing?: T;
              align?: T;
              color?: T;
            };
        tablet?:
          | T
          | {
              visibility?: T;
              anchor?: T;
              x?: T;
              y?: T;
              w?: T;
              h?: T;
              fontSize?: T;
              lineHeight?: T;
              fontWeight?: T;
              letterSpacing?: T;
              align?: T;
              color?: T;
            };
        mobile?:
          | T
          | {
              visibility?: T;
              anchor?: T;
              x?: T;
              y?: T;
              w?: T;
              h?: T;
              fontSize?: T;
              lineHeight?: T;
              fontWeight?: T;
              letterSpacing?: T;
              align?: T;
              color?: T;
            };
        animation?: T;
        delay?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * SVG or PNG. Falls back to the inline SVG below when empty.
   */
  logo?: (number | null) | Media;
  /**
   * Used when no logo image is set. Must include a viewBox; width/height are applied from the fields below.
   */
  logoSvg?: string | null;
  logoHref?: string | null;
  logoWidthDesktop?: number | null;
  logoWidthTablet?: number | null;
  logoWidthMobile?: number | null;
  logoOffsetYDesktop?: number | null;
  logoOffsetYWidescreen?: number | null;
  logoOffsetYMobile?: number | null;
  /**
   * Extra space the source site adds around the logo above 1760px.
   */
  logoMarginLeftWidescreen?: number | null;
  logoMarginRightWidescreen?: number | null;
  /**
   * Positive moves the menu right.
   */
  navShiftWidescreen?: number | null;
  navItems?:
    | {
        label: string;
        href: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  background?: string | null;
  linkColor?: string | null;
  /**
   * The source site uses the same colour, i.e. no hover effect.
   */
  linkActiveColor?: string | null;
  linkFontSize?: number | null;
  linkLineHeight?: number | null;
  linkPaddingX?: number | null;
  linkPaddingY?: number | null;
  /**
   * The menu is centred inside this column, next to the logo.
   */
  navWidthPercent?: number | null;
  logoGap?: number | null;
  heightWidescreen?: number | null;
  heightDesktop?: number | null;
  heightTablet?: number | null;
  heightMobile?: number | null;
  sticky?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'whatsapp' | 'snapchat' | 'tiktok' | 'youtube' | 'linkedin';
        href: string;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        href: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  separator?: string | null;
  background?: string | null;
  iconColor?: string | null;
  linkColor?: string | null;
  /**
   * Tint laid over the background colour.
   */
  overlayColor?: string | null;
  overlayOpacity?: number | null;
  iconBoxSize?: number | null;
  iconSize?: number | null;
  linkFontSize?: number | null;
  padTopDesktop?: number | null;
  /**
   * Space below the links (120 + 40 on the source site).
   */
  padBottomDesktop?: number | null;
  /**
   * Inline offset applied to the centred block.
   */
  sideOffsetDesktop?: number | null;
  gutterDesktop?: number | null;
  padTopTablet?: number | null;
  padBottomTablet?: number | null;
  sideOffsetTablet?: number | null;
  gutterTablet?: number | null;
  padTopMobile?: number | null;
  padBottomMobile?: number | null;
  sideOffsetMobile?: number | null;
  gutterMobile?: number | null;
  linksMarginTop?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteUrl?: string | null;
  locale?: string | null;
  direction?: ('rtl' | 'ltr') | null;
  themeColor?: string | null;
  bodyBackground?: string | null;
  favicon?: (number | null) | Media;
  defaultTitle?: string | null;
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  whatsappEnabled?: boolean | null;
  whatsappNumber?: string | null;
  whatsappColor?: string | null;
  whatsappSize?: number | null;
  whatsappIconSize?: number | null;
  whatsappInset?: number | null;
  gtmId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  logoSvg?: T;
  logoHref?: T;
  logoWidthDesktop?: T;
  logoWidthTablet?: T;
  logoWidthMobile?: T;
  logoOffsetYDesktop?: T;
  logoOffsetYWidescreen?: T;
  logoOffsetYMobile?: T;
  logoMarginLeftWidescreen?: T;
  logoMarginRightWidescreen?: T;
  navShiftWidescreen?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  background?: T;
  linkColor?: T;
  linkActiveColor?: T;
  linkFontSize?: T;
  linkLineHeight?: T;
  linkPaddingX?: T;
  linkPaddingY?: T;
  navWidthPercent?: T;
  logoGap?: T;
  heightWidescreen?: T;
  heightDesktop?: T;
  heightTablet?: T;
  heightMobile?: T;
  sticky?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  separator?: T;
  background?: T;
  iconColor?: T;
  linkColor?: T;
  overlayColor?: T;
  overlayOpacity?: T;
  iconBoxSize?: T;
  iconSize?: T;
  linkFontSize?: T;
  padTopDesktop?: T;
  padBottomDesktop?: T;
  sideOffsetDesktop?: T;
  gutterDesktop?: T;
  padTopTablet?: T;
  padBottomTablet?: T;
  sideOffsetTablet?: T;
  gutterTablet?: T;
  padTopMobile?: T;
  padBottomMobile?: T;
  sideOffsetMobile?: T;
  gutterMobile?: T;
  linksMarginTop?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  locale?: T;
  direction?: T;
  themeColor?: T;
  bodyBackground?: T;
  favicon?: T;
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  whatsappEnabled?: T;
  whatsappNumber?: T;
  whatsappColor?: T;
  whatsappSize?: T;
  whatsappIconSize?: T;
  whatsappInset?: T;
  gtmId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}